### PR TITLE
A newsweek clone - Build with Bootstrap 4 & HTML

### PR DESCRIPTION
**Pull request by idgm5**
Using Bootstrap 4, I cloned the [Newsweek](https://newsweek.com) official website following the instructions required by [The Odin Project](https://www.theodinproject.com/courses/html5-and-css3/lessons/using-bootstrap) and [Microverse Curriculum](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/65938290/).

Any new changes will be documented and pushed on this pull request.

### CODE REVIEW

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes ♻️ 🚥 

Hi @ghamtre, great work with this project 👍 congratulations for making this project 🙂 Let us make this project even better. Find comments below:
* Let us use bootstrap classes for everything, including margins, paddings, etc
* Let us add ```hover``` effects as it is in the original, since we are making a clone of the original page
* Kindly refactor the css file to avoid repeating properties
*  Currently, the project is not responsive to ```medium``` screen size. Kindly compare the images to the original and apply the changes accordingly 😄 
mdnav
```Original version```
mdnav1
```Currently```
culerr1
```Original version```
culerr
```Currently```
mdep
```Original version```
mdep1
```Currently```
mdfss
```Original version```
mdfss1
```Currently```
mdft
```Original version```
mdft1
```Currently```
mditm
```Original version```
mditm1
```Currently```
mdms
```Original version```
mdms1
```Currently```
mdot
```Original version```
mdot1
```Currently```
mdtf1
```Original version```
mdtf
* ```Small screen size```
   - We are missing newsletter header
newl1
```Original version```
newl
```Our version```
ficon
```Original version```
ficon1

Kindly make these changes and submit another code review 🙂 
_Happy coding_ 👨‍💻 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo)

**Comment by idgm5** [comment]
Hi @addod19, thanks for your review. 
Can I ask what is the resolution are you using for medium screens? 

Currently in my browser is working fine for medium screens (up to 800px) - Also for all the columns, I'm using bootstrap col-md as the documentation says. 

https://getbootstrap.com/docs/4.0/layout/grid/

You can try a default medium screen using "ipad" with the inspector browser.

**Comment by thsvr** [comment]
### **Status: CHANGES REQUIRED** :muscle: :muscle: 

Hi @ghamtre :smile: :smile: 

Good job on the implementations requested for you do, you are almost there. However there are just 2 things to fix before we can approve your project. Please read carfully the next few instructions. 

:v: Answering your question, the resolution for medium screen should be  around 768px :smile_cat: 

:v: The logo on your footer is not completely showing up and there is orange scroll on the botton of your page. Can you please fix it? I took a print to show clearly the 2 mentioned points: 

student

:v: Seems that your previuos fixed almost broken the left margin. Take a look on the next print and please fix it:

student2




### **Suggestions for the next projects:**
:v:  You can create a feature branch with a more descriptive name, like ''main-page'' or ''apple-page'' instead of ''development'', for example. It will be more descriptive and the appropriate use of ''develop'' or ''development'' branch will be introduced to you in the next section, Ruby. :smile_cat: 

_If you have any questions, don't hesitate to contact me through slack_ [@Thaís Vieira Azevedo](url)


### **Happy coding and good luck on the next review** :desktop_computer: :computer_mouse: 




**_Project reviewd by Thaís Vieira (TSE)_**

**Review by euqueme — CHANGES_REQUESTED** [review]
> ### Pull Request Under the review by Maria Eugenia Queme P. (TSE)

### Hello @ghamtre :handshake: 

### Thank you for doing the changes requested by previous reviewers :medal_sports: your project is looking better and better every time :art: You have done everything the previous reviewer asked you to do so I have no other choice but to approve the changes :heavy_check_mark: 

[OPTIONAL]

###  Your page still needs work to do on the breakpoints that are evident in the original page so I strongly recommend working on them  :point_down: 

## Small screens

**Section Positioning**

- [ ] Please follow the structure for the first 6 sections in this screen size:

1. TOP STORY
2. FEATURED STORIES
3. OPINION
4. MORE STORIES
5. CULTURE & TRAVEL
6. LATEST NEWS

Hint: [use bootstrap  flex-column-reverse](https://getbootstrap.com/docs/4.4/utilities/flex/) to accomplish this.

- Yours

image

- Original

image

#### CULTURE & TRAVEL

- [ ] The articles should take 100% of the screen width 

Hint: they should be [col-12](https://getbootstrap.com/docs/4.4/layout/grid/#how-it-works)

- Yours

image

- Original

image

#### IN THE MAGAZINE

- [ ] The preview magazine should be bigger in height in this screen size and the SEE ALL FEATURES > caption should be centered and with a smaller font 

- Yours

image

-Original

image

Hint: bootstrap doesn't have classes to accomplish this so you need to use a custom media query but let's keep the bootstrap breakpoint for small screens which is width < 576px

#### Footer

- [ ] The logo, copyright, and social icons should be in separate rows and aligned to the left for this screen size

Hint: each should be [col-12](https://getbootstrap.com/docs/4.4/layout/grid/#how-it-works)

- Yours

image

- Original

image

## Medium screens

### SUBSCRIBE and NEWSLETTER

- [ ] the images should take 25-30% of the screen width and the content 75-80%  

Hint: images should be col-md-3 and content should be col-md-9

- Yours

image

- Original

image

## Bootstrap breakpoints

Answering to the question you made on top, the project is about using bootstrap and you should use it everywhere even if the breakpoints don't fit 100% with the original you should only use media queries for selectors that don't support bootstrap breakpoints (like colors, height or decorations) but always stick to the bootstrap breakpoints you can find it all in the [documentation](https://getbootstrap.com/docs/4.4/getting-started/introduction/) but here is the chart with the breakpoints

image

### That's it! :raised_hands: 

### Please :pray: do this changes :man_technologist: (or not) and merge this branch when you are done :memo: 

Happy coding! :rocket: 

PROJECT STATUS: APPROVED :green_apple:

**Pull request merged**
